# Generated by Django 5.0 on 2024-10-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='timestamp',
            field=models.CharField(max_length=15),
        ),
    ]
