# Generated by Django 5.1.3 on 2024-11-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_withdrawal_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bet',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
